package view;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import model.Usuario;

/**
 *
 * @author Jonas
 */
public class Menu extends javax.swing.JFrame {

    private static Usuario usuario;
            
    public Menu(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        //setExtendedState(MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon  = new ImageIcon(getClass().getResource("/imagens/fundotopo2.jpg"));
        Image image = icon.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){
            public void paintComponet(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jmPedidos = new javax.swing.JMenu();
        jmiAbrir = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmiPedAberto = new javax.swing.JMenuItem();
        jmCadastros = new javax.swing.JMenu();
        jmAdministracao = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setResizable(false);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
        );

        jmPedidos.setText("Pedidos");

        jmiAbrir.setText("Abrir");
        jmiAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAbrirActionPerformed(evt);
            }
        });
        jmPedidos.add(jmiAbrir);
        jmPedidos.add(jSeparator1);

        jmiPedAberto.setText("Aberto");
        jmiPedAberto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPedAbertoActionPerformed(evt);
            }
        });
        jmPedidos.add(jmiPedAberto);

        jMenuBar1.add(jmPedidos);

        jmCadastros.setText("Cadastros");
        jMenuBar1.add(jmCadastros);

        jmAdministracao.setText("Administração");
        jMenuBar1.add(jmAdministracao);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAbrirActionPerformed
        PedidosAbrir jiPedidosAbrir = new PedidosAbrir();
        jDesktopPane1.add(jiPedidosAbrir);
        jiPedidosAbrir.setVisible(true);
        jiPedidosAbrir.setPosicao();
        
    }//GEN-LAST:event_jmiAbrirActionPerformed

    private void jmiPedAbertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPedAbertoActionPerformed
        PedidosAberto jiPedidosAberto = new PedidosAberto();
        jDesktopPane1.add(jiPedidosAberto);
        jiPedidosAberto.setVisible(true);
        jiPedidosAberto.setPosicao(); // Centraliza a Tela Interna
    }//GEN-LAST:event_jmiPedAbertoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Usuario usuario = null;
                new Menu(usuario).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu jmAdministracao;
    private javax.swing.JMenu jmCadastros;
    private javax.swing.JMenu jmPedidos;
    private javax.swing.JMenuItem jmiAbrir;
    private javax.swing.JMenuItem jmiPedAberto;
    // End of variables declaration//GEN-END:variables

    public static Usuario getUsuario() {
        return usuario;
    }

    public  void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
}
