/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PedidoDAO;
import java.awt.Dimension;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Pedido;

/**
 *
 * @author Jonas
 */
public class PedidosDetalhe extends javax.swing.JInternalFrame {

    /**
     * Creates new form PedidosDetalhe
     */
    public PedidosDetalhe(int id) {
        initComponents();
        // Chama o metodo listarDetalhes do PedidoDAO passando o usuário de login e id dp pedido como parametro
        preencherTabela(new PedidoDAO().listarDetalhes(Menu.getUsuario(), id));
        // Preenche o label pedido com o pedido selecionado na tela PedidosAberto
        lblVPedido.setText(String.valueOf(id));
        
        setValorPedido(new PedidoDAO().listarDetalhes(Menu.getUsuario(), id));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalhesPedido = new javax.swing.JTable();
        lblPedido = new javax.swing.JLabel();
        lblVPedido = new javax.swing.JLabel();
        lblVTotalPedido = new javax.swing.JLabel();
        lblTotalPedido = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        tblDetalhesPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód. Item", "Descrição Item", "Qtd Item", "Valor Un.", "Valor Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDetalhesPedido.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tblDetalhesPedido);

        lblPedido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPedido.setText("Pedido:");

        lblVPedido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lblVTotalPedido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lblTotalPedido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotalPedido.setText("Total Pedido:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotalPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVTotalPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPedido)
                        .addComponent(lblVPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTotalPedido)
                        .addComponent(lblVTotalPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPedido;
    private javax.swing.JLabel lblTotalPedido;
    private javax.swing.JLabel lblVPedido;
    private javax.swing.JLabel lblVTotalPedido;
    private javax.swing.JTable tblDetalhesPedido;
    // End of variables declaration//GEN-END:variables

    public void preencherTabela(Pedido p) {
        if (p != null) {
            
            //Configura a tabela
            DefaultTableModel m = (DefaultTableModel) tblDetalhesPedido.getModel();
            tblDetalhesPedido.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblDetalhesPedido.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblDetalhesPedido.getColumnModel().getColumn(2).setPreferredWidth(50);
            tblDetalhesPedido.getColumnModel().getColumn(3).setPreferredWidth(50);
            tblDetalhesPedido.getColumnModel().getColumn(4).setPreferredWidth(100);

            for (int i = 0; i < p.getItem().length; i++) {
                m.addRow(new Object[]{p.getItem(i).getId(), p.getItem(i).getDesc(), p.getQtdItem(i).getQtdItem(), String.format("%.2f", p.getItem(i).getValor()), String.format("%.2f", (p.getQtdItem(i).getQtdItem() * p.getItem(i).getValor()))});
            }
            tblDetalhesPedido.setModel(m);
            
            
        }
    }

    // Centraliza o JInternalFrame quando chamado
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    private void setValorPedido(Pedido p) {
        float valorPedido = 0;
        
        DecimalFormat df = new DecimalFormat("0.00");
        
        for (int i = 0; i < tblDetalhesPedido.getRowCount(); i++) {
            valorPedido += p.getQtdItem(i).getQtdItem() * p.getItem(i).getValor();
        }
        
        lblVTotalPedido.setText(df.format(valorPedido));
    }
}
