/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PedidoDAO;
import java.awt.Dimension;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Pedido;

/**
 *
 * @author User
 */
public class PedidosAberto extends javax.swing.JInternalFrame {
    
    public PedidosAberto() {
        initComponents();
        // Chama o metodo listar do PedidoDAO passando o usuário de login como parametro
        preencherTabela(new PedidoDAO().listar(Menu.getUsuario()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedido = new javax.swing.JTable();
        btnDetalhes = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(595, 316));

        tblPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pedido", "Mesa", "Data", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPedido.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tblPedido);
        if (tblPedido.getColumnModel().getColumnCount() > 0) {
            tblPedido.getColumnModel().getColumn(0).setPreferredWidth(20);
            tblPedido.getColumnModel().getColumn(1).setPreferredWidth(10);
            tblPedido.getColumnModel().getColumn(2).setPreferredWidth(50);
            tblPedido.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        btnDetalhes.setText("Detalhes");
        btnDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalhesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(btnDetalhes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnDetalhes)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalhesActionPerformed
        // Pega o indice da linha selecionada
        int indiceLinha = tblPedido.getSelectedRow();
        if(indiceLinha != -1){
        //Passa como parametro o id do pedido que gostaria de ver os detalhes
        PedidosDetalhe jiPedidosDetalhe = new PedidosDetalhe((int) tblPedido.getValueAt(indiceLinha, 0));
        Menu.jDesktopPane1.add(jiPedidosDetalhe);
        jiPedidosDetalhe.setVisible(true);
        jiPedidosDetalhe.setPosicao();  // Centraliza a Tela Interna
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um pedido !");
        }
    }//GEN-LAST:event_btnDetalhesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalhes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPedido;
    // End of variables declaration//GEN-END:variables

    public void preencherTabela(List<Object> lista) {
        if (lista != null) {
            if (lista.size() > 0) {
                
                //Configura a tabela
                DefaultTableModel m = (DefaultTableModel) tblPedido.getModel();
                tblPedido.getColumnModel().getColumn(0).setPreferredWidth(50);
                tblPedido.getColumnModel().getColumn(1).setPreferredWidth(50);
                tblPedido.getColumnModel().getColumn(2).setPreferredWidth(100);
                tblPedido.getColumnModel().getColumn(3).setPreferredWidth(100);

                for (Object obj : lista) {
                    Pedido p = (Pedido) obj;
                    m.addRow(new Object[]{p.getId(), p.getMesa().getId(), p.getData(),String.format("%.2f",p.getValor())});

                }
                tblPedido.setModel(m);
            }

        }
    }
    
    // Centraliza o JInternalFrame quando chamado
    public void setPosicao(){
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

}
