package view;

import controller.ProdutoDAO;
import controller.ProdutoVendaDAO;
import controller.VendaDAO;
import java.awt.Dimension;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.ApenasNumeros;
import model.Produto;
import model.ProdutoVenda;
import model.Venda;

public class VendaAbrir extends javax.swing.JInternalFrame {

    DecimalFormat dm = new DecimalFormat("0.00");

    public VendaAbrir() {
        initComponents();
        configurarFormulario();

        txtDesconto.setDocument(new ApenasNumeros());
        preencherTabelaProduto(new ProdutoDAO().listarAtivos(Menu.getUsuario()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblProdutosDisponiveis = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduto = new javax.swing.JTable();
        lblPesquisarPRoduto = new javax.swing.JLabel();
        rdbPorId = new javax.swing.JRadioButton();
        rdbPorDescricao = new javax.swing.JRadioButton();
        txtPesquisa = new javax.swing.JTextField();
        lblPesquisarPRoduto1 = new javax.swing.JLabel();
        spQtd = new javax.swing.JSpinner();
        btnAdicionar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProdutoVenda = new javax.swing.JTable();
        lblPordutosIncVenda = new javax.swing.JLabel();
        btnExcluirItem = new javax.swing.JButton();
        btnGerarVenda = new javax.swing.JButton();
        lblDesconto = new javax.swing.JLabel();
        lblTotalVenda = new javax.swing.JLabel();
        lblVlTotalVenda = new javax.swing.JLabel();
        txtDesconto = new javax.swing.JTextField();
        jdcData = new com.toedter.calendar.JDateChooser();
        lblData = new javax.swing.JLabel();

        setIconifiable(true);
        setResizable(true);

        lblProdutosDisponiveis.setText("Produtos Disponiveis");

        tblProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Descrição", "Qtde", "Preço"
            }
        ));
        jScrollPane1.setViewportView(tblProduto);

        lblPesquisarPRoduto.setText("Pesquisar Produto");

        buttonGroup1.add(rdbPorId);
        rdbPorId.setText("Por Id");

        buttonGroup1.add(rdbPorDescricao);
        rdbPorDescricao.setText("Por Descrição");

        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });

        lblPesquisarPRoduto1.setText("Quantidade:");

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        tblProdutoVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Descrição", "Qtde Disp", "Qtde", "Preço Un", "Preço Total"
            }
        ));
        jScrollPane2.setViewportView(tblProdutoVenda);

        lblPordutosIncVenda.setText("Produtos incluidos na venda");

        btnExcluirItem.setText("Excluir");
        btnExcluirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirItemActionPerformed(evt);
            }
        });

        btnGerarVenda.setText("Gerar");
        btnGerarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarVendaActionPerformed(evt);
            }
        });

        lblDesconto.setText("Desconto:");

        lblTotalVenda.setText("Total Venda:");

        txtDesconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescontoKeyReleased(evt);
            }
        });

        lblData.setText("Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblPesquisarPRoduto)
                                .addGap(85, 85, 85))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtPesquisa)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdbPorId)
                                        .addGap(28, 28, 28)
                                        .addComponent(rdbPorDescricao)))
                                .addGap(44, 44, 44))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPesquisarPRoduto1)
                                .addGap(18, 18, 18)
                                .addComponent(spQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAdicionar))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProdutosDisponiveis)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDesconto)
                    .addComponent(lblTotalVenda))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblVlTotalVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDesconto, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGerarVenda)
                .addGap(108, 108, 108))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(633, 633, 633)
                        .addComponent(btnExcluirItem))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPordutosIncVenda)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdcData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProdutosDisponiveis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPesquisarPRoduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdbPorId)
                            .addComponent(rdbPorDescricao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPesquisarPRoduto1))
                        .addGap(30, 30, 30)
                        .addComponent(btnAdicionar)))
                .addGap(32, 32, 32)
                .addComponent(lblPordutosIncVenda)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnExcluirItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblData)))
                .addGap(7, 7, 7)
                .addComponent(jdcData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDesconto)
                            .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTotalVenda)
                            .addComponent(lblVlTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnGerarVenda))
                .addGap(18, 46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // Pega o indice da linha selecionada
        int indiceLinha = tblProduto.getSelectedRow();
        if (indiceLinha != -1) {
            if (verificaExistenciaProdutoItem((int) tblProduto.getValueAt(indiceLinha, 0)) == false) {

                String qtdString = (String) tblProduto.getValueAt(indiceLinha, 2); // pega o valor do item e tranforma numa string
                qtdString = qtdString.replaceAll("\\,", "."); // substitui virgula por ponto
                float qtdFloat = Float.valueOf(qtdString); // acrescenta o valor em float

                if (((int) spQtd.getValue()) > 0 && ((int) spQtd.getValue()) <= qtdFloat) {
                    Produto p = new Produto();
                    // Obtem os valores do item selecionado
                    p.setId((int) tblProduto.getValueAt(indiceLinha, 0));
                    p.setDescricao((String) tblProduto.getValueAt(indiceLinha, 1));

                    String valorProduto = (String) tblProduto.getValueAt(indiceLinha, 3); // pega o valor do item e tranforma numa string
                    valorProduto = valorProduto.replaceAll("\\,", "."); // substitui virgula por ponto
                    p.setPreco(Float.valueOf(valorProduto)); // acrescenta o valor em float

                    String Qtdproduto = (String) tblProduto.getValueAt(indiceLinha, 2); // pega o valor do item e tranforma numa string
                    Qtdproduto = Qtdproduto.replaceAll("\\,", "."); // substitui virgula por ponto
                    p.setQtd(Float.valueOf(Qtdproduto)); // acrescenta o valor em float

                    ProdutoVenda pv = new ProdutoVenda();
                    pv.setQtdProduto((int) spQtd.getValue());

                    preencherTabelaProdutoVenda(p, pv);

                    setTotalVenda();
                } else {
                    JOptionPane.showMessageDialog(null, "Selecione uma quantidade entre 1 e " + tblProduto.getValueAt(indiceLinha, 2));
                }
            } else {
                JOptionPane.showMessageDialog(null, "Item já incluido !");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um item !");
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnExcluirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirItemActionPerformed
        if (tblProdutoVenda.getSelectedRow() != -1) {
            // Remove item selecionado da tabel itemPedido 
            ((DefaultTableModel) tblProdutoVenda.getModel()).removeRow(tblProdutoVenda.getSelectedRow());
            setTotalVenda();
        }
    }//GEN-LAST:event_btnExcluirItemActionPerformed

    private void txtDescontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescontoKeyReleased
        setTotalVenda();
    }//GEN-LAST:event_txtDescontoKeyReleased

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        if (rdbPorId.isSelected()) {
            if (txtPesquisa.getText().isEmpty() == true) {
                //Exclui todas as linhas da tabela
                while (tblProduto.getModel().getRowCount() > 0) {
                    DefaultTableModel m = (DefaultTableModel) tblProduto.getModel();
                    m.removeRow(0);
                }
                preencherTabelaProduto(new ProdutoDAO().listarAtivos(Menu.getUsuario()));
            } else {
                //Exclui todas as linhas da tabela
                while (tblProduto.getModel().getRowCount() > 0) {
                    DefaultTableModel m = (DefaultTableModel) tblProduto.getModel();
                    m.removeRow(0);
                }
                try {
                    int id = Integer.parseInt(txtPesquisa.getText());
                    preencherTabelaProduto(new ProdutoDAO().pesquisarPorId(Menu.getUsuario(), id));

                } catch (Exception e) {
                }
            }
        } else if (rdbPorDescricao.isSelected()) {
            if (txtPesquisa.getText().isEmpty() == true) {
                //Exclui todas as linhas da tabela
                while (tblProduto.getModel().getRowCount() > 0) {
                    DefaultTableModel m = (DefaultTableModel) tblProduto.getModel();
                    m.removeRow(0);
                }
                preencherTabelaProduto(new ProdutoDAO().listarAtivos(Menu.getUsuario()));
            } else {
                //Exclui todas as linhas da tabela
                while (tblProduto.getModel().getRowCount() > 0) {
                    DefaultTableModel m = (DefaultTableModel) tblProduto.getModel();
                    m.removeRow(0);
                }
                try {
                    String desc = txtPesquisa.getText();
                    preencherTabelaProduto(new ProdutoDAO().pesquisarPorDescricao(Menu.getUsuario(), desc));
                } catch (Exception e) {
                }
            }

        }
    }//GEN-LAST:event_txtPesquisaKeyReleased

    private void btnGerarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarVendaActionPerformed
        if (tblProdutoVenda.getRowCount() != 0) {
            int count;
            // Conta quantos itens serao adicionados
            count = tblProdutoVenda.getRowCount();
            String DescontoString = txtDesconto.getText(); // pega o valor do item e tranforma numa string

            Venda v = new Venda();
            v.setIdCliente(1);
            v.setDataVenda(jdcData.getDate());

            if ((DescontoString.isEmpty()) || DescontoString.equals(",")) {
                v.setDesconto(0);
            } else {
                String descontoString = txtDesconto.getText(); // pega o valor do desconto
                descontoString = descontoString.replaceAll("\\,", "."); // substitui virgula por ponto
                v.setDesconto(Float.valueOf(descontoString)); // acrescenta o valor em float                
            }

            String TotalString = lblVlTotalVenda.getText(); // pega o valor do total do pedido
            TotalString = TotalString.replaceAll("\\,", "."); // substitui virgula por ponto
            v.setValor(Float.valueOf(TotalString)); // acrescenta o valor em float

            ProdutoVenda pv[] = new ProdutoVenda[count];
            Produto p[] = new Produto[count];

            // For para acrescentar os itens as variáveis
            for (int x = 0; x < count; x++) {
                pv[x] = new ProdutoVenda();
                p[x] = new Produto();

                pv[x].setIdProduto((int) tblProdutoVenda.getValueAt(x, 0)); // pega o id do produto
                p[x].setId((int) tblProdutoVenda.getValueAt(x, 0)); // pega o id do produto                  

                String qtdDispString = (String) tblProdutoVenda.getValueAt(x, 2); // pega a qtd disponivel do produto e tranforma numa string
                qtdDispString = qtdDispString.replaceAll("\\,", "."); // substitui virgula por ponto
                p[x].setQtd(Float.valueOf(qtdDispString)); // acrescenta o valor em float 

                String qtdString = (String) tblProdutoVenda.getValueAt(x, 3); // pega a qtd do produto e tranforma numa string
                qtdString = qtdString.replaceAll("\\,", "."); // substitui virgula por ponto
                pv[x].setQtdProduto(Float.valueOf(qtdString)); // acrescenta o valor em float

                String valoUnString = (String) tblProdutoVenda.getValueAt(x, 4); // pega o valor do produto e tranforma numa string
                valoUnString = valoUnString.replaceAll("\\,", "."); // substitui virgula por ponto
                pv[x].setValorProduto(Float.valueOf(valoUnString)); // acrescenta o valor em float  
            }

            v.setId(new VendaDAO().inserir(Menu.getUsuario(), v));

            System.out.println(v.getId());

            if (v.getId() != -1) {
                for (int i = 0; i < pv.length; i++) {
                    pv[i].setIdVenda(v.getId());
                }
                int res = (new ProdutoVendaDAO().inserir(Menu.getUsuario(), pv));
                if (res != -1) {
                    for (int i = 0; i < p.length; i++) {
                        p[i].setQtd(p[i].getQtd() - pv[i].getQtdProduto());
                        new ProdutoDAO().atualizarEstoque(Menu.getUsuario(), p[i]);
                    }
                    JOptionPane.showMessageDialog(null, "Venda " + v.getId() + " gerado com sucesso");
                    while (tblProdutoVenda.getModel().getRowCount() > 0) {
                        DefaultTableModel dtm = (DefaultTableModel) tblProdutoVenda.getModel();
                        dtm.removeRow(0);
                    }
                    while (tblProduto.getModel().getRowCount() > 0) {
                        DefaultTableModel dtm = (DefaultTableModel) tblProduto.getModel();
                        dtm.removeRow(0);
                    }
                    preencherTabelaProduto(new ProdutoDAO().listarAtivos(Menu.getUsuario()));
                    txtDesconto.setText("");
                    lblVlTotalVenda.setText("0,00");
                    spQtd.setValue(1);
                    jdcData.setDate(null);
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "Nenhum produto adicionado ao pedido  !");
        }
    }//GEN-LAST:event_btnGerarVendaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnExcluirItem;
    private javax.swing.JButton btnGerarVenda;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdcData;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDesconto;
    private javax.swing.JLabel lblPesquisarPRoduto;
    private javax.swing.JLabel lblPesquisarPRoduto1;
    private javax.swing.JLabel lblPordutosIncVenda;
    private javax.swing.JLabel lblProdutosDisponiveis;
    private javax.swing.JLabel lblTotalVenda;
    private javax.swing.JLabel lblVlTotalVenda;
    private javax.swing.JRadioButton rdbPorDescricao;
    private javax.swing.JRadioButton rdbPorId;
    private javax.swing.JSpinner spQtd;
    private javax.swing.JTable tblProduto;
    private javax.swing.JTable tblProdutoVenda;
    private javax.swing.JTextField txtDesconto;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables

    private void configurarFormulario() {
        this.setTitle("Abrir Venda - New Fantasy");
        this.setResizable(false);
        this.setClosable(true);
        this.setIconifiable(true);
    }

    public void configurarTabelaItem() {
        //Configura a tabela e a posição dos itens na coluna
        DefaultTableModel m = (DefaultTableModel) tblProduto.getModel();

        tblProduto.getColumnModel().getColumn(0).setPreferredWidth(15);
        tblProduto.getColumnModel().getColumn(1).setPreferredWidth(150);
        tblProduto.getColumnModel().getColumn(2).setPreferredWidth(15);
        tblProduto.getColumnModel().getColumn(3).setPreferredWidth(15);
        DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer();
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        DefaultTableCellRenderer direita = new DefaultTableCellRenderer();
        esquerda.setHorizontalAlignment(SwingConstants.LEFT);
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        direita.setHorizontalAlignment(SwingConstants.RIGHT);
        tblProduto.getColumnModel().getColumn(2).setCellRenderer(direita);
        tblProduto.getColumnModel().getColumn(3).setCellRenderer(direita);

        tblProduto.setModel(m);
    }

    public void configurarTabelaItemPedido() {
        //Configura a tabela e a posição dos itens na coluna
        DefaultTableModel m = (DefaultTableModel) tblProdutoVenda.getModel();
        tblProdutoVenda.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblProdutoVenda.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblProdutoVenda.getColumnModel().getColumn(2).setPreferredWidth(50);
        tblProdutoVenda.getColumnModel().getColumn(3).setPreferredWidth(50);
        tblProdutoVenda.getColumnModel().getColumn(4).setPreferredWidth(100);
        tblProdutoVenda.getColumnModel().getColumn(5).setPreferredWidth(100);
        DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer();
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        DefaultTableCellRenderer direita = new DefaultTableCellRenderer();
        esquerda.setHorizontalAlignment(SwingConstants.LEFT);
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        direita.setHorizontalAlignment(SwingConstants.RIGHT);
        tblProdutoVenda.getColumnModel().getColumn(2).setCellRenderer(direita);
        tblProdutoVenda.getColumnModel().getColumn(3).setCellRenderer(direita);
        tblProdutoVenda.getColumnModel().getColumn(4).setCellRenderer(direita);
        tblProdutoVenda.getColumnModel().getColumn(5).setCellRenderer(direita);

        tblProdutoVenda.setModel(m);
    }

    public void preencherTabelaProdutoVenda(Produto p, ProdutoVenda pv) {
        if (p != null) {

            configurarTabelaItemPedido();
            DefaultTableModel m = (DefaultTableModel) tblProdutoVenda.getModel();

            m.addRow(new Object[]{p.getId(), p.getDescricao(), dm.format(p.getQtd()), dm.format(pv.getQtdProduto()), dm.format(p.getPreco()), dm.format(pv.getQtdProduto() * p.getPreco())});

            tblProdutoVenda.setModel(m);

        }
    }

    public void setTotalVenda() {
        int count = tblProdutoVenda.getRowCount();
        float totalVenda = 0;

        String DescontoString = txtDesconto.getText(); // pega o valor do item e tranforma numa string

        for (int x = 0; x < count; x++) {
            String valorTotalvenda = (String) tblProdutoVenda.getValueAt(x, 4); // pega o valor do item e tranforma numa string
            valorTotalvenda = valorTotalvenda.replaceAll("\\,", "."); // substitui virgula por ponto
            totalVenda += Float.valueOf(valorTotalvenda); // acrescenta o valor em float            
        }

        if ((DescontoString.isEmpty()) || DescontoString.equals(",")) {
            lblVlTotalVenda.setText(dm.format(totalVenda));

        } else {

            DescontoString = DescontoString.replaceAll("\\,", "."); // substitui virgula por ponto
            float valorDescontoFloat = Float.valueOf(DescontoString); // acrescenta o valor em float   

            if (valorDescontoFloat == 0) {
                lblVlTotalVenda.setText(dm.format(totalVenda));
            } else {
                totalVenda -= valorDescontoFloat;
                lblVlTotalVenda.setText(dm.format(totalVenda));
            }
        }
    }

    public void preencherTabelaProduto(List<Produto> lista) {
        if (lista != null) {

            //Configura a tabela e a posição dos itens na coluna
            configurarTabelaItem();
            DefaultTableModel m = (DefaultTableModel) tblProduto.getModel();

            for (Object obj : lista) {
                Produto p = (Produto) obj;
                m.addRow(new Object[]{p.getId(), p.getDescricao(), dm.format(p.getQtd()), dm.format(p.getPreco())});

            }
            tblProduto.setModel(m);

        }
    }

    public boolean verificaExistenciaProdutoItem(int idItem) {
        int totalLinhas = tblProdutoVenda.getRowCount();
        boolean jaExiste = false;

        // Verifica se existem itens adicionados
        if (totalLinhas != -1) {
            // Se houver itens adicionados da tabela item pedido verifica se o id do item a ser adicionado é igual a algum id já adicionado
            for (int i = 0; i < totalLinhas; i++) {
                if (idItem == (int) (tblProdutoVenda.getValueAt(i, 0))) {
                    jaExiste = true;
                }
            }
            return jaExiste;
        } else {
            return false;
        }

    }

    // Centraliza o JInternalFrame quando chamado
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

}
